# Generated by Django 5.2 on 2025-05-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventslist',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
