# Generated by Django 5.2 on 2025-05-31 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_indoor_outdoor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InDoor',
        ),
        migrations.DeleteModel(
            name='OutDoor',
        ),
        migrations.AddField(
            model_name='eventslist',
            name='indoor',
            field=models.ImageField(blank=True, null=True, upload_to='indoorimg/'),
        ),
        migrations.AddField(
            model_name='eventslist',
            name='outdoor',
            field=models.ImageField(blank=True, null=True, upload_to='outdoorimg/'),
        ),
    ]
