# Generated by Django 5.2 on 2025-06-10 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonVegMenu200',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NonVegMenu250',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VegMenu150',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VegMenu200',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
            ],
        ),
    ]
