# Generated by Django 5.2 on 2025-06-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_nonvegmenu200_nonvegmenu250_vegmenu150_vegmenu200'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='menu_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
