# Generated by Django 5.2 on 2025-06-12 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_booking_menu_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='total_person',
        ),
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='total_persons',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='venue_type',
            field=models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.eventslist'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='menu_type',
            field=models.CharField(choices=[('veg150', 'Veg Menu 150'), ('veg200', 'Veg Menu 200'), ('nonveg200', 'Non-Veg Menu 200'), ('nonveg250', 'Non-Veg Menu 250')], max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time_slot',
            field=models.CharField(max_length=50),
        ),
    ]
