# Generated by Django 5.2 on 2025-06-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_nonvegmenu200_vegmenu150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='menu_type',
            field=models.CharField(choices=[('veg150', 'Veg Menu 150'), ('nonveg200', 'Non-Veg Menu 200')], max_length=50),
        ),
    ]
